export const environment = {
    name:"mocksocketdebugbackend",
    production: false,
    remoteStreamer:true,
    mockSocket:true, // if false need to set socket url in children
    localSocket:false,
    remoteSocket:false,
    socketUrl:"",
    socketServerHttpUrl:"",
    mockBackend:false, // if false need to set backend url in children
    backendUrl:"...",
    backendApi:"...",
    smilesApi:"...",
    stickersApi:"....",
    animationsBaseUrl:"...",
    getUserMediaInfoUrl:"",
    buyMediaUrl:"",
    getBoughtMediaUrl:"",
    getLadyUnboughtMediaUrl:"",
    getUnboughtMediaUrl:"",
    getUserMediaByIdUrl:"",
    getUserMediaUrlUrl:"",
    detectUserMediaBoughtUrl:"",
    previewReviewedUrl:"",
    getTotalPreviewReviewsUrl:"",
    getTotalPreviewReviewsUrl:"",
    getUnsentMediaOfferUrl:"",
    onOfferSentUrl:"",
    manSelectedLadyInConversationListUrl:"",
};