export const environment = {
  name:"base",
  production: false,
  remoteStreamer:true,
  streamerUrl:"...",
  streamerPath:"...",
  mockSocket:false, // if false need to set socket url in children
  localSocket:false,
  remoteSocket:false,
  socketUrl:"unset",
  socketServerHttpUrl:"unset",
  mockBackend:false, // if false need to set backend url in children
  backendUrl:"unset",
  backendApi:"",
  smilesApi:"",
  stickersApi:"",
  animationsBaseUrl:"",
  getUserMediaInfoUrl:"...",
  buyMediaUrl:"...",
  getBoughtMediaUrl:"...",
  getLadyUnboughtMediaUrl:"...",
  getUnboughtMediaUrl:"...",
  getUserMediaByIdUrl:"...",
  getUserMediaUrlUrl:"...",
  detectUserMediaBoughtUrl:"...",
  previewReviewedUrl:"...",
  getTotalPreviewReviewsUrl:"...",
  getUnsentMediaOfferUrl:"http://localhost:3000/...",
  onOfferSentUrl:"http://localhost:3000/...",
  manSelectedLadyInConversationListUrl:"http://localhost:3000/...",
};