export const environment = {
  name:"localsocketdebugbackend",
  production: false,
  remoteStreamer:true,
  mockSocket:false, // if false need to set socket url in children
  localSocket:true,
  remoteSocket:false,
  socketUrl:"http://localhost:3000",
  socketServerHttpUrl:"http://localhost:3000",
  mockBackend:false, // if false need to set backend url in children
  backendUrl:"...",
  backendApi:"...",
  smilesApi:"...",
  stickersApi:"...",
  animationsBaseUrl:"...",
  getUserMediaInfoUrl:"...",
  buyMediaUrl:"...",
  getLadyUnboughtMediaUrl:"...",
  getBoughtMediaUrl:"...",
  getUnboughtMediaUrl:"...",
  getUserMediaByIdUrl:"...",
  getUserMediaUrlUrl:"...",
  detectUserMediaBoughtUrl:"...",
  previewReviewedUrl:"...",
  getTotalPreviewReviewsUrl:"...",
  getUnsentMediaOfferUrl:"...",
  onOfferSentUrl:"...",
  manSelectedLadyInConversationListUrl:"...",
};