export const environment = {
    name:"mocksocketmockbackend",
    production: false,
    remoteStreamer:true,
    mockSocket:true, // if false need to set socket url in children
    localSocket:false,
    remoteSocket:false,
    socketUrl:"",
    socketServerHttpUrl:"",
    mockBackend:true, // if false need to set backend url in children
    backendUrl:"",
    backendApi:"",
    smilesApi:"",
    stickersApi:"",
    animationsBaseUrl:"",
    getUserMediaInfoUrl:"",
    getUserMediaUrlUrl:"",
    buyMediaUrl:"",
    getLadyUnboughtMediaUrl:"",
    getBoughtMediaUrl:"",
    getUnboughtMediaUrl:"",
    getUserMediaByIdUrl:"",
    detectUserMediaBoughtUrl:"",
    previewReviewedUrl:"",
    getTotalPreviewReviewsUrl:"",
    getUnsentMediaOfferUrl:"",
    onOfferSentUrl:"",
    manSelectedLadyInConversationListUrl:"",
};