export const environment = {
    name:"remotedebugsocketdebugbackend",
    production: false,
    remoteStreamer:true,
    mockSocket:false, // if false need to set socket url in children
    localSocket:false,
    remoteSocket:true,
    socketUrl:"...",
    socketServerHttpUrl:"...",
    mockBackend:false, // if false need to set backend url in children
    backendUrl:"...",
    backendApi:"...",
    smilesApi:"...",
    stickersApi:"...",
    animationsBaseUrl:"...",
    getUserMediaInfoUrl:"...",
    buyMediaUrl:"...",
    getBoughtMediaUrl:"...",
    getLadyUnboughtMediaUrl:"...",
    getUnboughtMediaUrl:"...",
    getUserMediaByIdUrl:"...",
    getUserMediaUrlUrl:"...",
    detectUserMediaBoughtUrl:"...",
    previewReviewedUrl:"...",
    getTotalPreviewReviewsUrl:"...",
    getUnsentMediaOfferUrl:"...",
    onOfferSentUrl:"...",
    manSelectedLadyInConversationListUrl:"...",
};