export class SocketEvent {
    public static SOCKET_SERVICE_INIT_COMPLETE:string = "SOCKET_SERVICE_INIT_COMPLETE";
    public static RECONNECTED:string = "RECONNECTED";
    public static CONNECTION_FAILED:string = "CONNECTION_FAILED";
    public static CONNECTION_ERROR:string = "CONNECTION_ERROR";
    
    public static ON_NO_CONNECTION:string = "ON_NO_CONNECTION";
    
    public static ON_DISCONNECT:string = "ON_DISCONNECT";
    public static ON_PERMANENT_DISCONNECT:string = "ON_PERMANENT_DISCONNECT";
    
    public static ON_RECONNECT_ATTEMPT:string = "ON_RECONNECT_ATTEMPT";
    public static ON_RECONNECTED:string = "ON_RECONNECTED";
    public static ON_RECONNECT_FAILED:string = "ON_RECONNECT_FAILED";
    
    public static ON_SOCKET_CONNECTED:string = "ON_SOCKET_CONNECTED";
    
    public static ON_CONNECT_USER:string = "ON_CONNECT_USER";
    public static ON_DISCONNECT_USER:string = "ON_DISCONNECT_USER";
    
    public static ON_SEND_MESSAGE_ERROR:string = "ON_SEND_MESSAGE_ERROR";
    public static ON_PRIVATE_MESSAGE_RECEIVED:string = "ON_PRIVATE_MESSAGE_RECEIVED";
    public static ON_SELF_MESSAGE_RECEIVED:string = "ON_SELF_MESSAGE_RECEIVED";
    public static ON_START_TEXT_CHAT:string = "ON_START_TEXT_CHAT";
    
    public static ON_DELETE_MESSAGE:string = "ON_DELETE_MESSAGE";
    public static ON_DELETE_SELF_MESSAGE:string = "ON_DELETE_SELF_MESSAGE";
    
    public static ON_START_CHAT:string = "ON_START_CHAT";
    public static ON_STOP_CHAT:string = "ON_STOP_CHAT";
    public static ON_END_CHAT_BY_MAN:string = "ON_END_CHAT_BY_MAN";
    
    public static ON_START_CHAT_FROM_INVITE:string = "ON_START_CHAT_FROM_INVITE";
    public static ON_TYPING_NOTIFICATION:string = "ON_TYPING_NOTIFICATION";
    public static ON_TEXT_CHAT_EMERGENCY_STOPPED:string = "ON_TEXT_CHAT_EMERGENCY_STOPPED";
    
    public static ON_UNREAD_MESSAGES:string = "ON_UNREAD_MESSAGES";
    public static ON_UNREAD_MESSAGES_COUNT:string = "ON_UNREAD_MESSAGES_COUNT";
    public static ON_UNREAD_MESSAGES_COLLECTION:string = "ON_UNREAD_MESSAGES_COLLECTION";
    public static ON_READ_PRIVATE_MESSAGE:string = "ON_READ_PRIVATE_MESSAGE";
    public static ON_CLOSE_PRIVATE_MESSAGE:string = "ON_CLOSE_PRIVATE_MESSAGE";
    public static ON_BLOCK_PRIVATE_MESSAGE:string = "ON_BLOCK_PRIVATE_MESSAGE";
    
    public static ON_UPDATE_BALANCE:string = "ON_UPDATE_BALANCE";
    public static ON_BALANCE_HAS_BEEN_REPLENISHED:string = "ON_BALANCE_HAS_BEEN_REPLENISHED";
    public static ON_NOT_ENOUGH_MONEY:string = "ON_NOT_ENOUGH_MONEY";
    public static ON_PARTICIPANT_OUT_OF_MONEY:string = "ON_PARTICIPANT_OUT_OF_MONEY";
    public static ON_SERVER_IS_IN_DEBUG_MODE:string = "ON_SERVER_IS_IN_DEBUG_MODE";
    public static CONNECTION_CREATED:string = "CONNECTION_CREATED";
    public static ON_DUPLICATE_CONNECTION_PREV_SOCKET_DISCONNECTED:string = "ON_DUPLICATE_CONNECTION_PREV_SOCKET_DISCONNECTED";
    
    public static ON_OPENED_AUDIO_STREAM:string = "ON_OPENED_AUDIO_STREAM";
    public static ON_OPEN_AUDIO_STREAM_ERROR:string = "ON_OPEN_AUDIO_STREAM_ERROR";
    public static ON_CLOSED_AUDIO_STREAM:string = "ON_CLOSED_AUDIO_STREAM";

    public static ON_OPENED_VIDEO_STREAM:string = "ON_OPENED_VIDEO_STREAM";
    public static ON_OPEN_VIDEO_STREAM_ERROR:string = "ON_OPEN_VIDEO_STREAM_ERROR";
    public static ON_CLOSED_VIDEO_STREAM:string = "ON_CLOSED_VIDEO_STREAM";
    
    public static ON_STOP_AUDIO:string = "ON_STOP_AUDIO";
    public static ON_STOP_VIDEO:string = "ON_STOP_VIDEO";
    
    public static ON_SUBSCRIBE_CHAT:string = "ON_SUBSCRIBE_CHAT";
    public static ON_UNSUBSCRIBE_CHAT:string = "ON_UNSUBSCRIBE_CHAT";
    
    public static ON_TEXT_CHAT_FREE_MINUTE_PAYMENT_STARTED:string = "ON_TEXT_CHAT_FREE_MINUTE_PAYMENT_STARTED";
    public static ON_TEXT_CHAT_NORMAL_PAYMENT_STARTED:string = "ON_TEXT_CHAT_NORMAL_PAYMENT_STARTED";
    public static ON_TEXT_CHAT_LADY_HAS_FREE_MINUTE:string = "ON_TEXT_CHAT_LADY_HAS_FREE_MINUTE";

    public static ON_TEXT_CHAT_STARTED:string = "ON_TEXT_CHAT_STARTED";
    public static ON_TEXT_CHAT_STOPPED:string = "ON_TEXT_CHAT_STOPPED";

    public static ON_OUTGOING_TEXT_CHAT_PAYMENT_STARTED:string = "ON_OUTGOING_TEXT_CHAT_PAYMENT_STARTED";
    public static ON_OUTGOING_TEXT_CHAT_PAYMENT_STOPPED:string = "ON_OUTGOING_TEXT_CHAT_PAYMENT_STOPPED";
    public static ON_INCOMING_TEXT_CHAT_PAYMENT_STARTED:string = "ON_INCOMING_TEXT_CHAT_PAYMENT_STARTED";
    public static ON_INCOMING_TEXT_CHAT_PAYMENT_STOPPED:string = "ON_INCOMING_TEXT_CHAT_PAYMENT_STOPPED";

    public static ON_AUDIO_HAS_BEEN_SUBSCRIBED:string = "ON_AUDIO_HAS_BEEN_SUBSCRIBED";
    public static ON_AUDIO_HAS_BEEN_UNSUBSCRIBED:string = "ON_AUDIO_HAS_BEEN_UNSUBSCRIBED";
    
    public static ON_VIDEO_HAS_BEEN_SUBSCRIBED:string = "ON_VIDEO_HAS_BEEN_SUBSCRIBED";
    public static ON_VIDEO_HAS_BEEN_UNSUBSCRIBED:string = "ON_VIDEO_HAS_BEEN_UNSUBSCRIBED";
    
    public static DISABLE_MEDIA:string = "DISABLE_MEDIA";
    public static ENABLE_MEDIA:string = "ENABLE_MEDIA";

    public static ON_OUTGOING_AUDIO_CHAT_PAYMENT_STARTED:string = "ON_OUTGOING_AUDIO_CHAT_PAYMENT_STARTED";
    public static ON_OUTGOING_AUDIO_CHAT_PAYMENT_STOPPED:string = "ON_OUTGOING_AUDIO_CHAT_PAYMENT_STOPPED";
    
    public static ON_INCOMING_AUDIO_CHAT_PAYMENT_STARTED:string = "ON_INCOMING_AUDIO_CHAT_PAYMENT_STARTED";
    public static ON_INCOMING_AUDIO_CHAT_PAYMENT_STOPPED:string = "ON_INCOMING_AUDIO_CHAT_PAYMENT_STOPPED";
    
    public static ON_TEST_CONTACTS:string = "ON_TEST_CONTACTS";
    
    public static CAN_START_VIDEO_REQUEST:string = "CAN_START_VIDEO_REQUEST";
    public static ON_CAN_START_VIDEO_RESPONSE:string = "ON_CAN_START_VIDEO_RESPONSE";
    
    //public static START_VIDEO_REQUEST:string = "START_VIDEO_REQUEST";
    public static ON_START_VIDEO_SUCCESS_RESPONSE:string = "ON_START_VIDEO_SUCCESS_RESPONSE";
    
    public static CAN_START_AUDIO_REQUEST:string = "CAN_START_AUDIO_REQUEST";
    public static ON_CAN_START_AUDIO_RESPONSE:string = "ON_CAN_START_AUDIO_RESPONSE";

    //public static START_AUDIO_REQUEST:string = "START_AUDIO_REQUEST";
    public static ON_START_AUDIO_SUCCESS_RESPONSE:string = "ON_START_AUDIO_SUCCESS_RESPONSE";

    public static ON_STOP_VIDEO_SUCCESS_RESPONSE:string = "ON_STOP_VIDEO_SUCCESS_RESPONSE";
    public static ON_STOP_AUDIO_SUCCESS_RESPONSE:string = "ON_STOP_AUDIO_SUCCESS_RESPONSE";

    
    public static ON_START_REMOTE_VIDEO_SUCCESS_RESPONSE:string = "ON_START_REMOTE_VIDEO_SUCCESS_RESPONSE";

    public static GET_AUDIO_PUBLISH_STATE:string = "GET_AUDIO_PUBLISH_STATE";
    
    public static GET_VIDEO_PUBLISH_STATE:string = "GET_VIDEO_PUBLISH_STATE";
    
    public static GET_SUBSCRIBE_STATE:string = "GET_SUBSCRIBE_STATE";
    
    public static GET_ALL_STATES:string = "GET_ALL_STATES";
    
    public static ON_AUDIO_STREAMS_COLLECTION:string = "ON_AUDIO_STREAMS_COLLECTION";
    public static ON_USER_AUDIO_PUBLISH_STATE_CHANGED:string = "ON_USER_AUDIO_PUBLISH_STATE_CHANGED";

    public static ON_VIDEO_STREAMS_COLLECTION:string = "ON_VIDEO_STREAMS_COLLECTION";
    public static ON_USER_VIDEO_PUBLISH_STATE_CHANGED:string = "ON_USER_VIDEO_PUBLISH_STATE_CHANGED";

    public static ON_OUTGOING_VIDEO_CHAT_PAYMENT_STARTED:string = "ON_OUTGOING_VIDEO_CHAT_PAYMENT_STARTED";
    public static ON_OUTGOING_VIDEO_CHAT_PAYMENT_STOPPED:string = "ON_OUTGOING_VIDEO_CHAT_PAYMENT_STOPPED";
    public static ON_INCOMING_VIDEO_CHAT_PAYMENT_STARTED:string = "ON_INCOMING_VIDEO_CHAT_PAYMENT_STARTED";
    public static ON_INCOMING_VIDEO_CHAT_PAYMENT_STOPPED:string = "ON_INCOMING_VIDEO_CHAT_PAYMENT_STOPPED";
    
    public static ON_DISABLED:string = "ON_DISABLED";
    public static ON_CLIENT_VERSION_ERROR:string = "ON_CLIENT_VERSION_ERROR";
    public static ON_MEDIA_STATES_ERROR:string = "ON_MEDIA_STATES_ERROR";
    public static TOO_FREQUENT_RECONNECTIONS:string = "TOO_FREQUENT_RECONNECTIONS";
    public static ADMIN_DROPPED:string = "ADMIN_DROPPED";
    public static ADMIN_CONNECTED:string = "ADMIN_CONNECTED";
    public static ADMIN_USER_AUDIO_PUBLISH_STATE_CHANGED:string = "ADMIN_USER_AUDIO_PUBLISH_STATE_CHANGED";
    public static ADMIN_USER_IDS:string = "ADMIN_USER_IDS";
    public static USERS_COLLECTION:string = "USERS_COLLECTION";
    public static USER_ADDED:string = "USER_ADDED";
    public static USER_REMOVED:string = "USER_REMOVED";
    public static PREVIEW_NOT_EXISTS:string = "PREVIEW_NOT_EXISTS";
    public static PREVIEW_MUST_BE_UPDATED:string = "PREVIEW_MUST_BE_UPDATED";
    
    public static TRANSPORT_CHANGED:string = "TRANSPORT_CHANGED";
    public static USER_MOOD_CHANGED:string = "USER_MOOD_CHANGED";

    constructor() {
        
    }
}